---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 9000
    name: php-fpm
    protocol: TCP
    targetPort: 9000
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80    
  selector:
    app: ttrss-app
  sessionAffinity: None
  type: ClusterIP
