apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/nodeport.yml
- resources/service.yml
- resources/deployment.yml
- resources/feed-updater.yml
- resources/git-updater.yml

configMapGenerator:
- name: nginx-config
  files:
  - configmap/nginx.conf
- name: app-config-php
  files:
  - configmap/config.php

generatorOptions:
  disableNameSuffixHash: true
